default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: ak-playground-front-end_development

test:
  <<: *default
  database: ak-playground-front-end_test
